const test = require('node:test');
const assert = require('node:assert/strict');
const { createApp } = require('../src/app');
const { items } = require('../scripts/seed');
const app = createApp();
let server; let base;
test('start test server', async () => { server = app.listen(0); await new Promise(resolve => server.once('listening', resolve)); base = `http://127.0.0.1:${server.address().port}`; });
test('health endpoint returns service status', async () => { const res=await fetch(`${base}/health`); assert.equal(res.status,200); assert.deepEqual(await res.json(),{status:'ok'}); });
test('auth endpoints reject malformed and unauthenticated requests', async () => { let res=await fetch(`${base}/auth/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'x@example.com',password:'123'})}); assert.equal(res.status,400); res=await fetch(`${base}/auth/update`,{method:'PATCH'}); assert.equal(res.status,401); });
test('search validates empty query without contacting MongoDB', async () => { const res=await fetch(`${base}/search`); assert.equal(res.status,400); assert.match((await res.json()).error,/required/); });
test('seed data has 16 fully described examples', () => { assert.equal(items.length,16); for(const item of items){assert.ok(item.title);assert.ok(item.description);assert.ok(item.category)} });
test('landing page is served', async () => { const res=await fetch(base); assert.equal(res.status,200); assert.match(await res.text(),/Good things deserve a second chance/); });
test('stop test server', async () => { await new Promise((resolve,reject)=>server.close(e=>e?reject(e):resolve())); });
